### ISSUE TITLE
Newer smartphones do not have hardware call or search button.

### ISSUE THREAD

**Issue by mofosyne** [xloem/qrstream#15]
For activation of the streaming sequences of qr code, you need to have the hardware buttons that I do not have.

There needs to be an onscreen button to activate the streaming sequence.

**Comment by xloem** [comment]
Hi,
The latest version is intended to use the camera and menu buttons rather than call and search.  Is that working for you?  Do you have these other buttons?

**Comment by mofosyne** [comment]
Not really. Its saying "Next:tap Camera, Search, or Call.". Btw I got it from F-droid as V1.1.1 .

I personally think there should be a button there regardless of the existence of hardware buttons or not, since that would be more convenient from a finger tap perspective. Plus the QR code is always square, and most screens are rectangular. 

Btw, the receive QR code only receives for clipboard? or is it also for files? I wonder if there is some protocol behind it. Before I discovered your project, I was trying a bit on my side with https://github.com/mofosyne/tagdrop , where I transferred files as if it was a "datauri" string. But admittedly that is horribly inefficient, still I think there is some things we can merge together in terms of concept at least. (Oh you might find it interesting that I am also listening for "data:" intent from zxing, so you can launch the datauri viewer from zxing official barcode reading app)

To keep it short, it would be nice if we can come to a futureproof agreement on a way to store/retrieve binary files on printed QR codes, that everyone can stick to (especially barcode readers). As in, it should encode the mediatype, compression, filename etc... which would inform the receiving device on how to treat the incoming stream of data (or more specifically for me, a sequence of barcodes on paper). This would be aimed at stuff like "paper pgp keys", or tiny "html javascript games" for geo-cache . Maybe the first QR code is the 'metadata'?

**Comment by xloem** [comment]
I'll look into the v1.1.1 issue -- the menu key should advance right now.  I agree that a touchscreen button is a better solution and I'd gladly accept a pull request.

QRStream receives and sends via both files and clipboards.  I believe the file is stored in /sdcard/Android/com.github.xloem.qrstream/cache/qrstream -- there's no interface to select it yet (pull requests).  It's also intended to capture file-open and file-save intents from other applications -- is this working for you?

Watch-It-and-Got-It (see links at top of readme) implemented a prefixing metadata QR code like you describe.  I haven't done this yet because I wanted to be compatible with other barcode readers that don't understand the format.  But it would be a great additional feature.  I'd ideally like a format that's either backwards compatible with whatever watch-it-and-got-it did, or matches a pre-existing metadata or header format used elsewhere.  Human-readable sounds nice too.

Zxing can't generate structured-append barcodes and reads the SA data in a corrupt way.  There's an ancient patch out there that needs to be cleaned up or reimplemented to match the standards of the project maintainer.

**Comment by xloem** [comment]
Here we go: 1.1.1 is not latest.  The newer version 1.1.2 uses camera and menu.

A touchscreen button is needed for devices which do not have even these buttons.

**Comment by mofosyne** [comment]
Aye. And I do not have these buttons, no camera or menu. Only return and home. Pull request pushed.

**Comment by xloem** [comment]
#20

**Comment by mofosyne** [comment]
okay, string resource extracted.
