### ISSUE TITLE
Quick question from tagdrop

### ISSUE THREAD

**Issue by mofosyne** [xloem/qrstream#26]
How did you include external file intent integrator from zxing in android studio? The wiki in zxing is too vague for me. Also I cannot find the jar file that you used for your qrstream.

https://github.com/mofosyne/tagdrop/issues/12

**Comment by xloem** [comment]
Hi,

I added a reference to intent-integrator in build.gradle: https://github.com/xloem/qrstream/blob/master/android/app/build.gradle#L32 .  If you are just using intents that's all you need -- you don't need core.  It's better to put in a specific version number rather than '3.+' as I did, so that different people compiling your project will produce more similar builds.

If you just want to do what QRStream does you could also send QRStream an intent to do it for you.
